import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  BarChart3,
  Bot,
  Building2,
  Check,
  ChevronDown,
  CircleAlert,
  ClipboardCheck,
  Crop,
  Download,
  FileImage,
  Globe2,
  HeartHandshake,
  ImageUp,
  Languages,
  PanelRight,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Upload,
  Wand2,
} from 'lucide-react';
import './styles.css';

const CONTACT_EMAIL = 'hello@qinghenai.com';
const CONTACT_WECHAT = 'artipsg';

const copy = {
  en: {
    navProduct: 'Product',
    navFeatures: 'Features',
    navUseCases: 'Use cases',
    navServices: 'Services',
    navGrowth: 'SEO/GEO',
    login: 'Send samples',
    start: 'Open tool',
    eyebrow: 'AI Image Humanizer & Realism Enhancer',
    title: 'Make AI generated photos look natural and real',
    subtitle:
      'QingHen AI helps reduce fake-looking skin, plastic texture, harsh edges, odd lighting and metadata noise before you publish AI-generated images.',
    privacyTitle: 'Browser-local by default',
    privacyBody: 'Images stay on your device for preview, file-signal review, visual tuning and export. No upload is required for the core workflow.',
    verifyTitle: 'Realism and provenance checks',
    verifyBody: 'Use post-export checks to understand file signals and review whether the image still looks obviously AI-made.',
    openaiCheck: 'OpenAI image verification',
    geminiCheck: 'Gemini manual SynthID check',
    uploadTitle: 'Drop an AI-generated image here',
    uploadHint: 'PNG, JPG or WebP. Processing preview stays in your browser.',
    choose: 'Choose file',
    demo: 'Use demo image',
    before: 'Before',
    after: 'After',
    ready: 'Readiness',
    export: 'Export',
    exportFormat: 'Export format',
    fileSignals: 'File signals',
    localClean: 'Local re-encode',
    cleanedEstimate: 'Estimated cleaned export',
    save: 'Save as new',
    adjust: 'Adjustments',
    texture: 'Texture realism',
    detail: 'Skin / detail',
    noise: 'Artifact smoothing',
    compression: 'Compression',
    aiAssist: 'Realism preset',
    auto: 'Humanize lightly',
    presets: 'Crop & platform presets',
    compliance: 'Realism & readiness',
    complianceScore: 'Export readiness score',
    good: 'Ready checks',
    context: 'Metadata review ready',
    provenance: 'Source note option kept',
    policy: 'Policy reminder',
    policyBody:
      'QingHen AI improves image realism, file hygiene and publishing readiness. It does not guarantee detector removal or platform approval.',
    useCasesLabel: 'Use cases',
    useCasesTitle: 'Built for AI images that need to feel credible',
    useCasesSub: 'Use QingHen AI before publishing portraits, product visuals, social posts, ads and studio previews generated by Midjourney, ChatGPT, Stable Diffusion, Flux or similar tools.',
    faqLabel: 'FAQ',
    faqTitle: 'AI image humanizer questions',
    resourcesTitle: 'AI image realism knowledge base',
    resourcesSub: 'Guides for search engines, AI answers and creators who want practical workflows for realistic AI images.',
    growthLabel: 'Enterprise SEO / GEO',
    growthTitle: 'Need your business to show up in AI search?',
    growthSub:
      'QingHen AI is also a working case study for SEO, GEO and AI-search content architecture. We help businesses become easier for Google, ChatGPT, Perplexity, Gemini and AI Overviews to understand, cite and recommend.',
    growthCta: 'View SEO/GEO services',
    growthContact: 'Request a GEO audit',
    vipLabel: 'Manual review service',
    vipTitle: 'Need deeper retouching or merchant batch work?',
    vipSub:
      'The free tool covers local realism tuning, file checks and exports. For portraits, product images, visible marks, metadata review or merchant batches, request a manual review before paying.',
    vipCta: 'Free review for 3 images',
    vipTrust: 'Only for images you own, created, licensed or are authorized to edit.',
    vipContact: 'Send sample images',
    contactLabel: 'Contact',
    contactTitle: 'Send samples or request a GEO audit',
    contactSub: 'Scan WeChat or email us with either 1-3 sample images for manual review, or your business website for an SEO/GEO visibility audit.',
    wechatLabel: 'WeChat',
    emailLabel: 'Email',
  },
  zh: {
    navProduct: '产品',
    navFeatures: '功能',
    navUseCases: '场景',
    navServices: '服务',
    navGrowth: 'SEO/GEO',
    login: '发样图咨询',
    start: '打开工具',
    eyebrow: 'AI 图片真人化与真实感增强工具',
    title: '让 AI 生成图更自然、更真实',
    subtitle:
      '清痕 AI 帮助降低假脸感、塑料皮肤、奇怪光影、过锐边缘和文件信号噪音，让生成图更适合真实发布和商业使用。',
    privacyTitle: '默认浏览器本地处理',
    privacyBody: '核心流程不上传图片：预览、文件信号检查、真实感调整和导出都优先在用户设备上完成。',
    verifyTitle: '真实感与来源信号检查',
    verifyBody: '导出后检查文件信号和视觉观感，判断图片是否仍然明显带有 AI 生成感。',
    openaiCheck: 'OpenAI 官方图片检测',
    geminiCheck: 'Gemini 手动 SynthID 检查',
    uploadTitle: '拖入一张 AI 生成图片',
    uploadHint: 'PNG、JPG、WebP，本地预览处理。',
    choose: '选择文件',
    demo: '使用示例图',
    before: '原图',
    after: '优化后',
    ready: '发布评分',
    export: '导出',
    exportFormat: '导出格式',
    fileSignals: '文件信号',
    localClean: '本地重编码',
    cleanedEstimate: '预估清理后导出',
    save: '另存版本',
    adjust: '优化参数',
    texture: '真实纹理',
    detail: '皮肤/细节',
    noise: '瑕疵平滑',
    compression: '压缩适配',
    aiAssist: '真实感预设',
    auto: '轻度真人化',
    presets: '裁切与平台预设',
    compliance: '真实感与发布检查',
    complianceScore: '导出准备度',
    good: '准备度检查',
    context: '元数据检查完成',
    provenance: '来源说明选项保留',
    policy: '产品边界',
    policyBody:
      '清痕 AI 用于提升图片真实感、文件卫生和发布准备度，不承诺绕过检测或保证平台审核结果。',
    useCasesLabel: '使用场景',
    useCasesTitle: '为需要可信视觉的 AI 图片而做',
    useCasesSub: '适合在发布 Midjourney、ChatGPT、Stable Diffusion、Flux 等工具生成的人像、商品图、社交封面、广告图和工作室样片前使用。',
    faqLabel: 'FAQ',
    faqTitle: 'AI 图片真人化常见问题',
    resourcesTitle: 'AI 图片真实感知识库',
    resourcesSub: '围绕用户真实搜索问题建立教程页面，让搜索引擎、AI 摘要和创作者理解清痕 AI 的用法。',
    growthLabel: '企业 SEO / GEO 服务',
    growthTitle: '想让企业出现在 AI 搜索和 Google 结果里？',
    growthSub:
      '清痕 AI 本身就是一个 SEO、GEO、AI Search 内容架构案例。我们可以帮助企业官网更容易被 Google、ChatGPT、Perplexity、Gemini 和 AI Overview 理解、引用和推荐。',
    growthCta: '查看 SEO/GEO 服务',
    growthContact: '咨询 GEO 诊断',
    vipLabel: '人工评估服务',
    vipTitle: '需要更深度的修图或商家批量处理？',
    vipSub:
      '免费工具适合本地真实感调整、文件检查和平台导出。复杂人像、商品图、可见标记、深度元数据复查和商家批量素材，可以先发图人工评估。',
    vipCta: '免费评估 3 张图',
    vipTrust: '仅处理你拥有版权、自己生成、已获授权或客户委托的图片。',
    vipContact: '发样图咨询',
    contactLabel: '联系咨询',
    contactTitle: '发样图或咨询 GEO 诊断',
    contactSub: '扫码加微信，或发送 1-3 张样图做人工评估；如果是企业 SEO/GEO 服务，请直接发官网地址，我们先做可见度诊断。',
    wechatLabel: '微信',
    emailLabel: '邮箱',
  },
};

const presets = [
  { id: 'x', labelEn: 'X', labelZh: 'X', mark: 'X', ratio: '16:9', color: '#111111', width: 1920, height: 1080 },
  { id: 'instagram', labelEn: 'Instagram', labelZh: 'Instagram', mark: 'I', ratio: '4:5', color: '#e94991', width: 1080, height: 1350 },
  { id: 'douyin', labelEn: 'Douyin', labelZh: '抖音', mark: '抖', ratio: '9:16', color: '#00d4d8', width: 1080, height: 1920 },
  { id: 'xiaohongshu', labelEn: 'RedNote', labelZh: '小红书', mark: '红', ratio: '3:4', color: '#ff2442', width: 1080, height: 1440 },
  { id: 'wechat-oa', labelEn: 'WeChat OA', labelZh: '公众号', mark: '微', ratio: '2.35:1', color: '#16b56f', width: 900, height: 383 },
  { id: 'custom', labelEn: 'Custom', labelZh: '自定义', mark: 'C', ratio: 'Original', color: '#8a8f98', width: null, height: null },
];

const resourceLinks = [
  { zh: '企业 SEO/GEO 服务', en: 'Enterprise SEO/GEO services', hrefZh: '/zh/seo-geo-services.html', hrefEn: '/en/seo-geo-services.html' },
  { zh: 'AI 图片真人化工具', en: 'AI image humanizer', hrefZh: '/zh/ai-image-humanizer.html', hrefEn: '/en/ai-image-humanizer.html' },
  { zh: '让 AI 图片变真实', en: 'Make AI photos look real', hrefZh: '/zh/make-ai-photo-look-real.html', hrefEn: '/en/make-ai-photo-look-real.html' },
  { zh: '去除 AI 感', en: 'Remove AI look from images', hrefZh: '/zh/remove-ai-look-from-image.html', hrefEn: '/en/remove-ai-look-from-image.html' },
  { zh: 'AI 头像真实化', en: 'AI portrait retouching', hrefZh: '/zh/ai-portrait-retouching.html', hrefEn: '/en/ai-portrait-retouching.html' },
  { zh: 'AI 图片元数据清理', en: 'AI image metadata guide', hrefZh: '/zh/ai-image-metadata-cleaner.html', hrefEn: '/en/c2pa-metadata-guide.html' },
  { zh: '清痕 AI 资源中心', en: 'QingHen AI resources', hrefZh: '/zh/seo-hub.html', hrefEn: '/en/seo-hub.html' },
];

const growthServices = [
  {
    icon: 'audit',
    zh: 'AI 搜索可见度诊断',
    en: 'AI search visibility audit',
    zhText: '检查品牌在 ChatGPT、Perplexity、Gemini、Google AI Overview 和传统搜索里的呈现问题。',
    enText: 'Check how your brand appears across ChatGPT, Perplexity, Gemini, Google AI Overviews and traditional search.',
  },
  {
    icon: 'architecture',
    zh: '官网 SEO/GEO 架构改造',
    en: 'SEO/GEO site architecture',
    zhText: '重做 Title、服务页、FAQ、Schema、内链、sitemap、llms.txt 和 AI 可读内容结构。',
    enText: 'Improve titles, service pages, FAQs, schema, internal links, sitemaps, llms.txt and AI-readable content structure.',
  },
  {
    icon: 'content',
    zh: '中英文内容增长系统',
    en: 'Bilingual content growth system',
    zhText: '围绕企业真实客户搜索意图，持续产出中英文行业页、案例页、问题页和知识库内容。',
    enText: 'Build English and Chinese industry pages, case studies, question-led pages and knowledge-base content around real buyer intent.',
  },
];

const useCases = [
  {
    zh: 'AI 人像和头像',
    en: 'AI portraits and headshots',
    zhText: '降低假脸感、塑料皮肤和过度磨皮，让头像更适合 LinkedIn、小红书和作品集。',
    enText: 'Reduce fake-face cues, plastic skin and over-smoothed details for LinkedIn, social profiles and portfolios.',
  },
  {
    zh: '电商和商品图',
    en: 'Ecommerce product visuals',
    zhText: '让 AI 商品图减少模板感和不自然光影，发布前导出更适合平台的尺寸。',
    enText: 'Make AI product visuals less template-like, less synthetic and easier to prepare for channel-specific exports.',
  },
  {
    zh: '广告和社交封面',
    en: 'Ads and social creatives',
    zhText: '修正过锐边缘、压缩噪点和颜色漂移，让封面、广告图和帖子更可信。',
    enText: 'Tune sharp edges, compression noise and color drift so ads, covers and posts feel more credible.',
  },
  {
    zh: '工作室批量素材',
    en: 'Studio batch review',
    zhText: '先用免费工具初筛，复杂图片再交给人工服务做深度修图和发布检查。',
    enText: 'Use the free tool for triage, then send complex images for manual retouching and publishing review.',
  },
];

const vipServices = [
  {
    icon: 'metadata',
    zh: '高级文件信号复查',
    en: 'Advanced file-signal review',
    descZh: 'EXIF、XMP、PNG chunks、C2PA 等深度检查，适合重要商业发布图。',
    descEn: 'Deeper EXIF, XMP, PNG chunks and C2PA review for important commercial images.',
    priceZh: '5-10 元/张起',
    priceEn: 'From $2/image',
  },
  {
    icon: 'mark',
    zh: '可见瑕疵和标记清理',
    en: 'Visible mark and artifact cleanup',
    descZh: '角标、logo、日期、文字覆盖等，需确认图片权利和背景复杂度。',
    descEn: 'Corner marks, logos, date stamps and text overlays with rights confirmation.',
    priceZh: '9.9-99 元/张',
    priceEn: '$5-$19/image',
  },
  {
    icon: 'natural',
    zh: 'AI 图片真人化精修',
    en: 'AI image humanizing retouch',
    descZh: '降低假脸感、塑料感、过锐、噪点和模板感，适合头像、封面和商品图。',
    descEn: 'Reduce fake-face cues, plastic texture, over-sharpening, noise and template-like results.',
    priceZh: '19.9 元/张起',
    priceEn: 'From $5/image',
  },
  {
    icon: 'batch',
    zh: '商家批量发布包',
    en: 'Merchant batch package',
    descZh: '小红书、公众号、朋友圈、电商多尺寸导出和批量图片体检。',
    descEn: 'Batch checks and exports for RedNote, WeChat Official Account, Douyin, social and ecommerce use.',
    priceZh: '99 元/30 张起',
    priceEn: 'From $29/pack',
  },
];

const faqs = [
  {
    zh: '清痕 AI 是 AI 生图工具吗？',
    en: 'Is QingHen AI an AI image generator?',
    zhAnswer: '不是。清痕 AI 更像 AI 图片真人化和发布前清理工具，用于优化已经生成好的图片。',
    enAnswer: 'No. QingHen AI is an AI image humanizer and pre-publishing cleanup tool for images you already generated.',
  },
  {
    zh: '它能让 AI 图片看起来像真实照片吗？',
    en: 'Can it make AI images look like real photos?',
    zhAnswer: '它可以降低过锐、塑料感、噪点和部分不自然纹理，但不能保证修复所有结构错误。',
    enAnswer: 'It can reduce over-sharpness, plastic texture, noise and some unnatural artifacts, but it cannot guarantee every structural issue is fixed.',
  },
  {
    zh: '图片会上传到服务器吗？',
    en: 'Does QingHen AI upload my images?',
    zhAnswer: '当前核心流程在浏览器本地完成，预览、调整、文件信号检查和导出不需要上传图片。',
    enAnswer: 'The current core workflow runs in your browser, so preview, tuning, file-signal checks and export do not require uploads.',
  },
  {
    zh: '它能保证图片不被识别为 AI 吗？',
    en: 'Can it guarantee an image will not be detected as AI?',
    zhAnswer: '不能。清痕 AI 只做真实感优化、文件卫生和发布准备，不承诺绕过检测或平台审核。',
    enAnswer: 'No. QingHen AI improves realism, file hygiene and publishing readiness, but it does not guarantee detector removal or platform approval.',
  },
];

function App() {
  const [lang, setLang] = useState('en');
  const [image, setImage] = useState('');
  const [fileName, setFileName] = useState('Demo image - AI generated draft');
  const [fileInfo, setFileInfo] = useState({
    type: 'image/svg+xml',
    size: 'Demo',
    dimensions: '1200 x 820',
    originalBytes: 0,
    cleanedEstimate: 'Ready after export',
    metadata: ['Demo preview: upload a PNG, JPG or WebP to inspect real file signals.'],
  });
  const [selectedPreset, setSelectedPreset] = useState('x');
  const [exportFormat, setExportFormat] = useState('image/png');
  const [activeTool, setActiveTool] = useState('Upload');
  const [settings, setSettings] = useState({
    texture: 34,
    detail: 28,
    noise: 42,
    compression: 18,
  });
  const fileRef = useRef(null);
  const canvasRef = useRef(null);
  const t = copy[lang];
  const activePreset = presets.find((item) => item.id === selectedPreset) || presets[0];

  const score = useMemo(() => {
    const base = 76 + Math.round((settings.texture + settings.detail + settings.noise) / 12);
    return Math.min(96, base - Math.max(0, settings.compression - 32));
  }, [settings]);

  const filter = useMemo(() => {
    const contrast = 100 + Math.round(settings.texture / 8);
    const saturate = 98 + Math.round(settings.detail / 7);
    const brightness = 100 + Math.round(settings.noise / 18);
    return `contrast(${contrast}%) saturate(${saturate}%) brightness(${brightness}%)`;
  }, [settings]);

  const displayImage =
    image ||
    'data:image/svg+xml;utf8,' +
      encodeURIComponent(`
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 820">
          <defs>
            <linearGradient id="sky" x1="0" y1="0" x2="1" y2="1">
              <stop stop-color="#b7d6df"/>
              <stop offset=".42" stop-color="#edf5f2"/>
              <stop offset="1" stop-color="#162a26"/>
            </linearGradient>
            <linearGradient id="lake" x1="0" y1=".45" x2="1" y2="1">
              <stop stop-color="#7fb0ad"/>
              <stop offset="1" stop-color="#10231f"/>
            </linearGradient>
          </defs>
          <rect width="1200" height="820" fill="url(#sky)"/>
          <path d="M0 420 L160 230 L290 410 L430 170 L620 430 L790 220 L950 430 L1200 250 L1200 820 L0 820 Z" fill="#3d5654"/>
          <path d="M0 454 L150 275 L290 454 L430 214 L620 454 L790 270 L950 454 L1200 300 L1200 820 L0 820 Z" fill="#e9f0ec" opacity=".45"/>
          <rect y="500" width="1200" height="320" fill="url(#lake)"/>
          <path d="M220 468 L340 390 L465 470 Z" fill="#32433d"/>
          <rect x="260" y="468" width="160" height="112" fill="#463a2d"/>
          <path d="M260 468 L340 390 L420 468 Z" fill="#252a29"/>
          <rect x="315" y="510" width="36" height="70" fill="#1d211f"/>
          <rect x="372" y="498" width="28" height="28" fill="#f7d88a"/>
          <g fill="#1d3b32">
            <path d="M92 485 l42 -150 l42 150z"/><path d="M106 485 l28 -92 l28 92z"/>
            <path d="M512 492 l42 -150 l42 150z"/><path d="M820 482 l52 -170 l52 170z"/>
            <path d="M985 490 l36 -120 l36 120z"/>
          </g>
          <g opacity=".35" fill="#ffffff">
            <circle cx="170" cy="150" r="26"/><circle cx="206" cy="138" r="35"/><circle cx="250" cy="155" r="27"/>
            <circle cx="740" cy="170" r="22"/><circle cx="770" cy="156" r="32"/><circle cx="810" cy="173" r="24"/>
          </g>
        </svg>
      `);

  async function handleFile(event) {
    const file = event.target.files?.[0];
    if (!file) return;
    setFileName(file.name);
    await inspectFile(file);
    const reader = new FileReader();
    reader.onload = () => setImage(String(reader.result));
    reader.readAsDataURL(file);
  }

  async function inspectFile(file) {
    const buffer = await file.arrayBuffer();
    const bytes = new Uint8Array(buffer.slice(0, Math.min(buffer.byteLength, 350000)));
    const ascii = Array.from(bytes, (byte) => (byte >= 32 && byte < 127 ? String.fromCharCode(byte) : '.')).join('');
    const lower = ascii.toLowerCase();
    const signals = [];

    if (lower.includes('exif')) signals.push('EXIF block detected');
    if (lower.includes('xmp') || lower.includes('adobe:ns:meta')) signals.push('XMP metadata marker detected');
    if (lower.includes('c2pa') || lower.includes('manifest')) signals.push('C2PA / manifest-like marker detected');
    if (lower.includes('synthid')) signals.push('SynthID text marker detected');
    if (lower.includes('itxt') || lower.includes('text') || lower.includes('ztxt')) signals.push('PNG text chunk marker detected');
    if (lower.includes('photoshop') || lower.includes('adobe')) signals.push('Editor/app metadata marker detected');

    const dimensions = await readImageDimensions(file);
    const cleanedBytes = Math.max(24000, Math.round(file.size * 0.72));
    setFileInfo({
      type: file.type || 'unknown image',
      size: formatBytes(file.size),
      dimensions,
      originalBytes: file.size,
      cleanedEstimate: formatBytes(cleanedBytes),
      metadata: signals.length ? signals : ['No obvious EXIF/XMP/C2PA text marker found in the sampled file header.'],
    });
  }

  function setAutoEnhance() {
    setSettings({ texture: 42, detail: 36, noise: 48, compression: 20 });
  }

  function exportImage() {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const canvas = canvasRef.current;
      const ctx = canvas.getContext('2d');
      const targetWidth = activePreset.width || img.naturalWidth || 1200;
      const targetHeight = activePreset.height || img.naturalHeight || 820;
      canvas.width = targetWidth;
      canvas.height = targetHeight;
      const sourceWidth = img.naturalWidth || targetWidth;
      const sourceHeight = img.naturalHeight || targetHeight;
      const scale = Math.max(targetWidth / sourceWidth, targetHeight / sourceHeight);
      const drawWidth = sourceWidth * scale;
      const drawHeight = sourceHeight * scale;
      const offsetX = (targetWidth - drawWidth) / 2;
      const offsetY = (targetHeight - drawHeight) / 2;
      ctx.filter = filter;
      ctx.drawImage(img, offsetX, offsetY, drawWidth, drawHeight);
      canvas.toBlob(
        (blob) => {
          if (!blob) return;
          const link = document.createElement('a');
          const extension = exportFormat.split('/')[1].replace('jpeg', 'jpg');
          link.download = fileName.replace(/\.[^.]+$/, '') + `-${selectedPreset}-qinghen.${extension}`;
          link.href = URL.createObjectURL(blob);
          link.click();
          window.setTimeout(() => URL.revokeObjectURL(link.href), 1200);
        },
        exportFormat,
        0.92,
      );
    };
    img.src = displayImage;
  }

  return (
    <main>
      <nav className="topbar">
        <a className="brand" href="#top" aria-label="QingHen AI">
          <span className="brand-mark">Q</span>
          <span>{lang === 'zh' ? '清痕 AI' : 'QingHen AI'}</span>
        </a>
        <div className="nav-links">
          <a href={lang === 'zh' ? '/zh/features.html' : '/en/features.html'}>{t.navProduct}</a>
          <a href={lang === 'zh' ? '/zh/local-image-processing.html' : '/en/local-image-processing.html'}>{t.navFeatures}</a>
          <a href={lang === 'zh' ? '/zh/xiaohongshu-ai-image-cleaner.html' : '/en/ai-image-metadata-cleaner.html'}>{t.navUseCases}</a>
          <a href={lang === 'zh' ? '/zh/seo-geo-services.html' : '/en/seo-geo-services.html'}>{t.navGrowth}</a>
          <a href="#services">{t.navServices}</a>
          <a href={lang === 'zh' ? '/zh/seo-hub.html' : '/en/seo-hub.html'}>{lang === 'zh' ? '资源' : 'Resources'}</a>
        </div>
        <div className="nav-actions">
          <button className="ghost" onClick={() => setLang(lang === 'zh' ? 'en' : 'zh')}>
            <Languages size={17} />
            {lang === 'zh' ? '中文' : 'English'}
            <ChevronDown size={15} />
          </button>
          <a className="login" href="#contact">{t.login}</a>
          <button className="primary" onClick={() => fileRef.current?.click()}>{t.start}</button>
        </div>
      </nav>

      <section className="hero" id="top">
        <div className="hero-copy">
          <p className="plain-label">
            <Sparkles size={16} />
            {t.eyebrow}
          </p>
          <h1>{t.title}</h1>
          <p className="subtitle">{t.subtitle}</p>
          <div className="feature-row">
            <Feature icon={<Wand2 />} title={lang === 'zh' ? '修复瑕疵' : 'Clean artifacts'} text={lang === 'zh' ? '降低塑料感、边缘噪点和过锐纹理' : 'Reduce plastic texture, noisy edges and over-sharp details'} />
            <Feature icon={<SlidersHorizontal />} title={lang === 'zh' ? '增强自然感' : 'Tune realism'} text={lang === 'zh' ? '按平台和素材类型调整细节' : 'Balance details for each channel'} />
            <Feature icon={<ShieldCheck />} title={lang === 'zh' ? '合规导出' : 'Compliant export'} text={lang === 'zh' ? '保留说明，不承诺绕过检测' : 'No evasion claims or hidden promises'} />
          </div>
        </div>
        <div className="drop-panel">
          <Upload size={34} />
          <strong>{t.uploadTitle}</strong>
          <span>{t.uploadHint}</span>
          <div className="drop-actions">
            <button onClick={() => fileRef.current.click()}>{t.choose}</button>
            <button className="secondary" onClick={() => setImage('')}>{t.demo}</button>
          </div>
          <input ref={fileRef} type="file" accept="image/*" onChange={handleFile} />
        </div>
      </section>

      <section className="studio-shell" aria-label="QingHen AI editor">
        <header className="studio-top">
          <div className="studio-title">
            <span className="back-button">‹</span>
            <span>Studio</span>
            <strong>{fileName}</strong>
          </div>
          <div className="toolbar">
            <button className="icon-button" aria-label="Original file" onClick={() => setActiveTool('Upload')}><FileImage size={18} /></button>
            <button className="zoom">100% <ChevronDown size={14} /></button>
            <button className="dark-button" onClick={exportImage}><Download size={16} /> {t.export}</button>
          </div>
        </header>

        <div className="studio-grid">
          <aside className="rail">
            {['Upload', 'Enhance', 'Crop', 'Compare', 'History'].map((tool) => (
              <RailIcon
                key={tool}
                icon={{ Upload: <ImageUp />, Enhance: <SlidersHorizontal />, Crop: <Crop />, Compare: <PanelRight />, History: <ClipboardCheck /> }[tool]}
                label={tool}
                active={activeTool === tool}
                onClick={() => setActiveTool(tool)}
              />
            ))}
          </aside>

          <section className="comparison">
            <div className="image-card">
              <span>{t.before}</span>
              <img src={displayImage} alt="Original uploaded preview" />
            </div>
            <div className="image-card">
              <span className="after-tag">{t.after}</span>
              <img src={displayImage} alt="Enhanced preview" style={{ filter }} />
              <div className="grain" />
            </div>
            <div className="file-strip">
              <img src={displayImage} alt="" />
              <div>
                <strong>{fileName}</strong>
                <p>{fileInfo.type} · {fileInfo.dimensions} · {fileInfo.size}</p>
              </div>
            </div>
          </section>

          <section className="adjustments">
            <div className="panel-header">
              <h2>{t.adjust}</h2>
              <button onClick={() => setSettings({ texture: 24, detail: 20, noise: 28, compression: 12 })}>Reset</button>
            </div>
            <Slider label={t.texture} value={settings.texture} onChange={(value) => setSettings({ ...settings, texture: value })} />
            <Slider label={t.detail} value={settings.detail} onChange={(value) => setSettings({ ...settings, detail: value })} />
            <Slider label={t.noise} value={settings.noise} onChange={(value) => setSettings({ ...settings, noise: value })} />
            <Slider label={t.compression} value={settings.compression} onChange={(value) => setSettings({ ...settings, compression: value })} />
            <div className="assist-box">
              <h3><Sparkles size={16} /> {t.aiAssist}</h3>
              <button onClick={setAutoEnhance}>{t.auto}</button>
              <p>{lang === 'zh' ? '按当前平台预设生成轻量优化建议。' : 'Applies light suggestions for the selected platform.'}</p>
            </div>
          </section>

          <section className="presets">
            <h2>{t.presets}</h2>
            <div className="preset-grid">
              {presets.map((preset) => (
                <button
                  key={preset.id}
                  className={selectedPreset === preset.id ? 'preset selected' : 'preset'}
                  onClick={() => setSelectedPreset(preset.id)}
                >
                  <span style={{ background: preset.color }}>{preset.mark}</span>
                  <strong>{lang === 'zh' ? preset.labelZh : preset.labelEn}</strong>
                  <small>{preset.ratio}</small>
                </button>
              ))}
            </div>
            <div className="crop-preview">
              <img src={displayImage} alt="Crop preview" style={{ filter }} />
              <div className="crop-box" />
            </div>
            <label className="select-label">
              {t.exportFormat}
              <select value={exportFormat} onChange={(event) => setExportFormat(event.target.value)}>
                <option value="image/png">PNG</option>
                <option value="image/jpeg">JPG</option>
                <option value="image/webp">WebP</option>
              </select>
            </label>
            <label className="select-label">
              Resolution
              <select value={selectedPreset} onChange={(event) => setSelectedPreset(event.target.value)}>
                {presets.map((preset) => (
                  <option key={preset.id} value={preset.id}>
                    {lang === 'zh' ? preset.labelZh : preset.labelEn} · {preset.width ? `${preset.width} x ${preset.height}` : 'original'}
                  </option>
                ))}
              </select>
            </label>
          </section>

          <section className="readiness">
            <h2>{t.compliance}</h2>
            <div className="score-card">
              <div className="score-ring" style={{ '--score': `${score * 3.6}deg` }}>
                <strong>{score}</strong>
                <span>/100</span>
              </div>
              <div>
                <p>{t.complianceScore}</p>
                <strong className="green">{score > 88 ? 'Excellent' : 'Ready'}</strong>
              </div>
            </div>
            <h3>{t.good}</h3>
            <CheckRow label="Resolution" value={activePreset.width ? `${activePreset.width} x ${activePreset.height}` : fileInfo.dimensions} />
            <CheckRow label={t.localClean} value="Canvas re-encode" />
            <CheckRow label={t.cleanedEstimate} value={fileInfo.cleanedEstimate} />
            <CheckRow label="Aspect ratio" value={presets.find((item) => item.id === selectedPreset)?.ratio || 'Free'} />
            <CheckRow label={t.context} value="Ready" />
            <CheckRow label={t.provenance} value="On" />
            <h3>{t.fileSignals}</h3>
            <div className="signal-list">
              {fileInfo.metadata.map((item) => (
                <p key={item}><FileImage size={13} /> {item}</p>
              ))}
            </div>
            <div className="policy-note">
              <CircleAlert size={18} />
              <div>
                <strong>{t.policy}</strong>
                <p>{t.policyBody}</p>
              </div>
            </div>
          </section>
        </div>
      </section>

      <section className="use-case-section" id="use-cases">
        <div className="section-copy">
          <p className="green-label">{t.useCasesLabel}</p>
          <h2>{t.useCasesTitle}</h2>
          <p>{t.useCasesSub}</p>
        </div>
        <div className="use-case-grid">
          {useCases.map((item) => (
            <article className="use-case-card" key={item.en}>
              <h3>{lang === 'zh' ? item.zh : item.en}</h3>
              <p>{lang === 'zh' ? item.zhText : item.enText}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="trust-flow">
        <article className="trust-card">
          <div className="trust-icon"><ShieldCheck size={24} /></div>
          <h2>{t.privacyTitle}</h2>
          <p>{t.privacyBody}</p>
          <ul>
            <li><Check size={15} /> {lang === 'zh' ? '不需要账户即可预览处理' : 'No account needed for preview processing'}</li>
            <li><Check size={15} /> {lang === 'zh' ? '文件不离开浏览器核心流程' : 'Files stay in-browser for the core workflow'}</li>
            <li><Check size={15} /> {lang === 'zh' ? '适合批量素材初筛' : 'Built for batch image triage'}</li>
          </ul>
        </article>
        <article className="trust-card">
          <div className="trust-icon"><Globe2 size={24} /></div>
          <h2>{t.verifyTitle}</h2>
          <p>{t.verifyBody}</p>
          <div className="verify-links">
            <a href="https://openai.com/research/verify/" target="_blank" rel="noreferrer">
              {t.openaiCheck}
            </a>
            <span>{lang === 'zh' ? 'Gemini 上传图片后询问是否含有 SynthID' : 'Upload to Gemini and ask whether the image has SynthID'}</span>
          </div>
        </article>
      </section>

      <section className="faq-section">
        <div className="section-copy">
          <p className="green-label">{t.faqLabel}</p>
          <h2>{t.faqTitle}</h2>
        </div>
        <div className="faq-grid">
          {faqs.map((item) => (
            <article className="faq-card" key={item.en}>
              <h3>{lang === 'zh' ? item.zh : item.en}</h3>
              <p>{lang === 'zh' ? item.zhAnswer : item.enAnswer}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="resource-section">
        <div className="section-copy">
          <p className="green-label">{lang === 'zh' ? 'SEO / GEO' : 'SEO / GEO'}</p>
          <h2>{t.resourcesTitle}</h2>
          <p>{t.resourcesSub}</p>
        </div>
        <div className="resource-grid">
          {resourceLinks.map((item) => (
            <a key={`${item.hrefEn}-${item.hrefZh}`} href={lang === 'zh' ? item.hrefZh : item.hrefEn}>
              {lang === 'zh' ? item.zh : item.en}
            </a>
          ))}
        </div>
      </section>

      <section className="growth-section" id="seo-geo">
        <div className="section-copy">
          <p className="green-label">{t.growthLabel}</p>
          <h2>{t.growthTitle}</h2>
          <p>{t.growthSub}</p>
          <div className="growth-actions">
            <a className="dark-link" href={lang === 'zh' ? '/zh/seo-geo-services.html' : '/en/seo-geo-services.html'}>
              {t.growthCta}
            </a>
            <a className="light-link" href="#contact">{t.growthContact}</a>
          </div>
        </div>
        <div className="growth-grid">
          {growthServices.map((service) => (
            <article className="growth-card" key={service.en}>
              <div className="growth-icon">
                {service.icon === 'audit' && <BarChart3 size={22} />}
                {service.icon === 'architecture' && <Bot size={22} />}
                {service.icon === 'content' && <Building2 size={22} />}
              </div>
              <h3>{lang === 'zh' ? service.zh : service.en}</h3>
              <p>{lang === 'zh' ? service.zhText : service.enText}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="vip-section" id="services">
        <div className="vip-heading">
          <div>
            <p className="green-label">{t.vipLabel}</p>
            <h2>{t.vipTitle}</h2>
            <p>{t.vipSub}</p>
          </div>
          <a className="vip-main-cta" href="#contact">
            <HeartHandshake size={17} />
            {t.vipCta}
          </a>
        </div>
        <div className="vip-grid">
          {vipServices.map((service) => (
            <article className="vip-card" key={service.en}>
              <div className="vip-icon">
                {service.icon === 'metadata' && <ShieldCheck size={22} />}
                {service.icon === 'mark' && <FileImage size={22} />}
                {service.icon === 'natural' && <Wand2 size={22} />}
                {service.icon === 'batch' && <SlidersHorizontal size={22} />}
              </div>
              <h3>{lang === 'zh' ? service.zh : service.en}</h3>
              <p>{lang === 'zh' ? service.descZh : service.descEn}</p>
              <strong>{lang === 'zh' ? service.priceZh : service.priceEn}</strong>
              <a href="#contact">
                {t.vipContact}
              </a>
            </article>
          ))}
        </div>
        <div className="contact-panel" id="contact">
          <div className="contact-copy">
            <p className="green-label">{t.contactLabel}</p>
            <h3>{t.contactTitle}</h3>
            <p>{t.contactSub}</p>
            <div className="contact-methods">
              <span>{t.wechatLabel}: <strong>{CONTACT_WECHAT}</strong></span>
              <a href={`mailto:${CONTACT_EMAIL}?subject=QingHen%20AI%20manual%20review`}>
                {t.emailLabel}: {CONTACT_EMAIL}
              </a>
            </div>
          </div>
          <img src="/contact-assets/wechat-artipsg-qr.jpg" alt="WeChat QR code for artipsg" />
        </div>
        <p className="vip-note">{t.vipTrust} {lang === 'zh' ? 'AI 辅助创作内容请按平台规则主动声明；不承诺绕过平台检测。' : 'Follow platform disclosure rules for AI-assisted content; no platform approval is guaranteed.'}</p>
      </section>

      <footer className="site-footer">
        <div>
          <strong>QingHen AI / 清痕 AI</strong>
          <p>{lang === 'zh' ? 'AI 图片真人化、真实感增强与发布前检查工具。' : 'AI image humanizing, realism enhancement and pre-publishing checks.'}</p>
        </div>
        <div className="footer-links">
          <a href="/privacy.html">Privacy</a>
          <a href="/terms.html">Terms</a>
          <a href={lang === 'zh' ? '/zh/faq.html' : '/en/faq.html'}>FAQ</a>
          <a href="#contact">Contact</a>
        </div>
      </footer>

      <canvas ref={canvasRef} hidden />
    </main>
  );
}

function Feature({ icon, title, text }) {
  return (
    <div className="feature">
      {React.cloneElement(icon, { size: 24 })}
      <div>
        <strong>{title}</strong>
        <p>{text}</p>
      </div>
    </div>
  );
}

function RailIcon({ icon, label, active, onClick }) {
  return (
    <button className={active ? 'rail-button active' : 'rail-button'} onClick={onClick}>
      {React.cloneElement(icon, { size: 19 })}
      <span>{label}</span>
    </button>
  );
}

function Slider({ label, value, onChange }) {
  return (
    <label className="slider">
      <span>
        {label}
        <b>+{value}</b>
      </span>
      <input type="range" min="0" max="60" value={value} onChange={(event) => onChange(Number(event.target.value))} />
    </label>
  );
}

function CheckRow({ label, value }) {
  return (
    <div className="check-row">
      <span><Check size={13} /></span>
      <p>{label}</p>
      <strong>{value}</strong>
    </div>
  );
}

function formatBytes(bytes) {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  return `${(bytes / 1024 ** index).toFixed(index === 0 ? 0 : 1)} ${units[index]}`;
}

function readImageDimensions(file) {
  return new Promise((resolve) => {
    const url = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      resolve(`${img.naturalWidth || 0} x ${img.naturalHeight || 0}`);
      URL.revokeObjectURL(url);
    };
    img.onerror = () => {
      resolve('Unknown');
      URL.revokeObjectURL(url);
    };
    img.src = url;
  });
}

createRoot(document.getElementById('root')).render(<App />);
